const INTEGRATED_TOPIC_BANK = [
 {topic:'الصفات والضمائر الإشارية',grammarId:'dimostrativi',focus:'questo / quello',example:'Questo libro è interessante, ma quello è più utile.',q:'في المثال، إيه الفرق الأساسي بين «questo» و«quello»؟',options:['هذا قريب وذاك أبعد','مذكر ومؤنث','مفرد وجمع','فاعل ومفعول'],correct:0,status:'complete'},
 {topic:'صفات الملكية',grammarId:'possessivi',focus:'mio / tuo / suo / nostro / vostro / loro',example:'Il mio libro, la tua penna e il loro progetto sono qui.',q:'صفة الملكية في الإيطالية بتتبع إيه؟',options:['الشيء المملوك في الجنس والعدد','المالك فقط','الفعل','زمن الجملة'],correct:0,status:'complete'},
 {topic:'أوقات اليوم',grammarId:'momenti_giornata',focus:'mattina / pomeriggio / sera / notte',example:'Studio dalla mattina alla sera e riposo di notte.',q:'«dalla mattina alla sera» معناها إيه؟',options:['من الصباح إلى المساء','كل صباح','بعد الظهر','منتصف الليل'],correct:0,status:'complete'},
 {topic:'الكلمات متعددة الوظائف',grammarId:'parole_multitasking',focus:'troppo / mezzo / qualcuno',example:'Qualcuno ha aspettato mezz’ora perché c’era troppo lavoro.',q:'«mezz’ora» معناها إيه؟',options:['نصف ساعة','ساعة ونصف','منتصف الليل','مرتين'],correct:0,status:'exposure'},
 {topic:'ظروف الزمن',grammarId:'avverbi_tempo',focus:'già / ancora / appena / mai / sempre / più',example:'Ho già finito, ma lui non ha ancora iniziato.',q:'في Passato Prossimo، «già» و«ancora» غالبًا بييجوا فين؟',options:['بين المساعد واسم المفعول','قبل الفاعل فقط','بعد المفعول فقط','آخر الجملة دائمًا'],correct:0,status:'complete'},
 {topic:'ظروف الكيفية',grammarId:'avverbio_modo',focus:'velocemente / in fretta',example:'Ha risposto velocemente e poi è uscito in fretta.',q:'ظرف الكيفية بيجاوب على أنهي سؤال؟',options:['كيف حدث الفعل؟','متى حدث؟','مَن فعل؟','كم العدد؟'],correct:0,status:'complete'},
 {topic:'الصفات',grammarId:'aggettivi_vari',focus:'veloce / migliore / diverso',example:'È un metodo diverso, ma il risultato è migliore.',q:'الصفة الإيطالية عادةً بتتبع الاسم في إيه؟',options:['الجنس والعدد','الزمن','الشخص فقط','حرف الجر'],correct:0,status:'exposure'},
 {topic:'حروف الجر غير الأصلية',grammarId:'improprie',focus:'prima di / dopo / durante',example:'Prima della lezione studio; durante la lezione ascolto; dopo torno a casa.',q:'«durante» معناها إيه؟',options:['أثناء','قبل','بعد','بدون'],correct:0,status:'complete'},
 {topic:'أدوات التجزئة والنكرة',grammarId:'partitivi',focus:'un / uno / una / dei / degli / delle',example:'Ho un libro, uno zaino e dei quaderni.',q:'«dei quaderni» معناها إيه؟',options:['بعض الدفاتر','دفتر واحد','الدفاتر كلها','لا دفاتر'],correct:0,status:'complete'},
 {topic:'حروف الوصل',grammarId:'congiunzioni',focus:'e / anche / pure / inoltre / né…né / ma / però / quindi / perché',example:'Anche Marco e pure Anna sono venuti; inoltre non mancavano né libri né quaderni, ma era tardi, quindi abbiamo continuato perché era importante.',q:'«né…né» وظيفتها إيه؟',options:['النفي المزدوج: لا…ولا','الإضافة فقط','تحديد المكان','السؤال'],correct:0,status:'exposure'},
 {topic:'الضمائر الإيطالية',grammarId:'pronomi_complemento',focus:'mi / ti / lo / la / ci / vi / gli / le',example:'Mi vede, ti chiama, gli parla e le scrive.',q:'«gli» في «gli parla» معناها إيه؟',options:['له','لها','لنا','إياها'],correct:0,status:'exposure'},
 {topic:'الأسماء',grammarId:'nomi_sostantivi',focus:'inizio / fine / volta / mezzo',example:'All’inizio abbiamo scelto un mezzo diverso; alla fine l’abbiamo usato una volta.',q:'«mezzo» هنا معناها إيه؟',options:['وسيلة','نصف فقط','نهاية','مرة'],correct:0,status:'exposure'},
 {topic:'أدوات الاستفهام',grammarId:'interrogativi',focus:'chi / dove / quando / quanto / quale / che cosa',example:'Chi viene, dove va, quando arriva e quale strada sceglie?',q:'«Chi?» بنسأل بيها عن إيه؟',options:['الأشخاص','الوقت','الكمية','المكان'],correct:0,status:'complete'},
 {topic:'أدوات التعريف',grammarId:'articoli_determinativi',focus:'il / lo / la / l’ / i / gli / le',example:'Il libro, lo zaino, l’amico, i quaderni e gli studenti.',q:'«lo» بتيجي قبل أنهي حالة؟',options:['s + ساكن أو z أو gn أو ps','كل اسم مؤنث','كل جمع','كل حرف متحرك'],correct:0,status:'complete'},
 {topic:'الضمائر غير المحددة',grammarId:'indefiniti',focus:'qualcuno / qualcosa / chiunque / nessuno / niente',example:'Qualcuno ha detto qualcosa, ma nessuno ha risposto.',q:'«nessuno» معناها إيه؟',options:['لا أحد','شخص ما','كل واحد','شيء ما'],correct:0,status:'complete'},
 {topic:'أيام الأسبوع',grammarId:'giorni_settimana',focus:'lunedì…domenica',example:'Studio dal lunedì al venerdì e riposo ogni domenica.',q:'«ogni domenica» معناها إيه؟',options:['كل يوم أحد','من الأحد','إلى الأحد','الأحد الماضي'],correct:0,status:'complete'}
];
const INTEGRATED_PREPOSITION_BANK = [];
function prep(form,meaning,example,kind='حرف جر'){INTEGRATED_PREPOSITION_BANK.push({form,meaning,example,kind,q:`في المثال «${example}»، معنى «${form}» إيه؟`,options:[meaning,'قبل','بدون','ضد'],correct:0});}
[['di','من / خاص بـ','Parliamo di grammatica.'],['a','إلى / في','Vado a scuola.'],['da','من / منذ','Studio da lunedì.'],['in','في / إلى','Sono in ufficio.'],['con','مع / بواسطة','Parlo con Marco.'],['su','على / عن','Il libro è su questo tavolo.'],['per','لـ / لمدة','Studio per due ore.'],['tra','بين / خلال','Sono tra amici.'],['fra','بين / بعد','Parto fra due giorni.']].forEach(x=>prep(...x,'حرف جر أصلي'));
[
 ['del','di + il','Il libro del professore.'],['dello','di + lo','La penna dello studente.'],['della','di + la','La porta della scuola.'],['dei','di + i / بعض','I quaderni dei ragazzi.'],['degli','di + gli / بعض','Gli zaini degli studenti.'],['delle','di + le / بعض','Le chiavi delle stanze.'],
 ['al','a + il','Vado al mercato.'],['allo','a + lo','Vado allo stadio.'],['alla','a + la','Vado alla stazione.'],['ai','a + i','Vado ai corsi.'],['agli','a + gli','Parlo agli studenti.'],['alle','a + le','Arrivo alle otto.'],
 ['dal','da + il','Torno dal mercato.'],['dallo','da + lo','Esco dallo studio.'],['dalla','da + la','Arrivo dalla stazione.'],['dai','da + i','Ricevo notizie dai colleghi.'],['dagli','da + gli','Imparo dagli errori.'],['dalle','da + le','Lavoro dalle otto.'],
 ['nel','in + il','Lavoro nel pomeriggio.'],['nello','in + lo','Aspetto nello studio.'],['nella','in + la','È nella cartella.'],['nei','in + i','Parliamo nei corridoi.'],['negli','in + gli','Aspetto negli uffici.'],['nelle','in + le','Dormiamo nelle stanze.'],
 ['sul','su + il','Il libro è sul tavolo.'],['sullo','su + lo','La borsa è sullo scaffale.'],['sulla','su + la','La chiave è sulla sedia.'],['sui','su + i','I documenti sono sui tavoli.'],['sugli','su + gli','I libri sono sugli scaffali.'],['sulle','su + le','Le note sono sulle pagine.']
].forEach(x=>prep(...x,'حرف جر مركب'));
[
 ['a destra','على اليمين','La banca è a destra.'],['a sinistra','على اليسار','La farmacia è a sinistra.'],['sopra','فوق','Il libro è sopra il tavolo.'],['sotto','تحت','Il gatto è sotto il letto.'],['dentro','داخل','Sono dentro la casa.'],['fuori','خارج','Aspetto fuori dall’ufficio.'],['dietro','خلف','La macchina è dietro l’autobus.'],['davanti a','أمام','Aspetto davanti al cinema.'],['lungo','بمحاذاة','Cammino lungo il fiume.'],['vicino a','قريب من','È vicino a me.'],['lontano da','بعيد عن','È lontano da casa.'],['prima di','قبل','Studio prima della lezione.'],['dopo','بعد','Torno dopo la scuola.'],['durante','أثناء','Ascolto durante la lezione.'],['verso','حوالي','Arrivo verso le otto.'],['fino a','حتى','Lavoro fino alle sei.'],['senza','بدون','Esco senza il telefono.'],['contro','ضد','Sono contro questa idea.'],['secondo','بحسب','Secondo me, è giusto.'],['oltre','بعد / وراء','La scuola è oltre il ponte.'],['nonostante','على الرغم من','Esco nonostante la pioggia.'],['tranne','ما عدا','Sono arrivati tutti tranne Marco.'],['eccetto','باستثناء','Mangio tutto eccetto il pesce.'],['salvo','باستثناء / ما عدا','Erano presenti tutti salvo Anna.'],['mediante','بواسطة','Pago mediante bonifico.'],['tramite','عن طريق','Invio il file tramite e-mail.']
].forEach(x=>prep(...x,'حرف جر غير أصلي'));
